name: dev-ci
on:
  push:
    branches:
      - main
jobs:
  deploy_ghpages:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.MY_HOST }} # 服务器IP（需要在GitHub上自行配置对应的secret）
          user: ${{ secrets.MY_USER }} # 服务器用户名
          pass: ${{ secrets.MY_PASS }} # 服务器密码
          port: 21
          connect_timeout: 10s
          local: "./*" # 源路径（工作流）
          remote: /usr/share/doc/HTML/        # 目标路径（服务器）
